g1 = Greeting.create(text: 'Hope you had a great day')
g2 = Greeting.create(text: 'The shirt looks great on you')
g3 = Greeting.create(text: 'How long did we met, great to see you again!')
g4 = Greeting.create(text: 'Welcome broooo')
g5 = Greeting.create(text: 'Nice to meet you')